export const IS_ADMIN = "IS_ADMIN";
export const EMPLOYEE_ID = "EMPLOYEE_ID";
export const IS_LOGIN = "IS_LOGIN";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILED = "DELETE_FAILED";

export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILED = "REFRESH_TOKEN_FAILED";

export const LOAD_NOTIFICATION = "LOAD_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const CLEAR_NOTIFICATION_STARTER = "CLEAR_NOTIFICATION_STARTER";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";